name: auto_router_tutorial
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.7

dev_dependencies:
  build_runner:
  auto_route_generator: ^0.6.8

flutter:
  uses-material-design: true